In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('boston_test.csv')
df.describe()

,2.91816626,-0.48772236,1.01599907,-0.27259857,0.36544404,-1.60934343,1.11749449,-1.04849446,1.66124525,1.53092646,0.80657583,-1.59755122,1.04106182
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,-0.082200,-0.003515,-0.116860,-0.084932,-0.089453,-0.084088,-0.124360,0.012197,-0.143450,-0.143857,-0.064207,0.060158,-0.063663
std,0.725217,1.008537,0.944068,0.842620,1.007191,0.992926,1.040549,0.918999,0.936121,0.925509,1.005848,0.950202,0.957340
min,-0.417173,-0.487722,-1.557842,-0.272599,-1.431329,-3.058221,-2.225199,-1.263551,-0.982843,-1.308051,-2.707379,-3.907193,-1.496084
25%,-0.410876,-0.487722,-0.898332,-0.272599,-0.947582,-0.566137,-1.249062,-0.756523,-0.637962,-0.785394,-0.765457,0.263128,-0.680272
50%,-0.398921,-0.487722,-0.406617,-0.272599,-0.299707,-0.122712,0.073792,-0.189764,-0.523001,-0.601276,0.113032,0.396098,-0.287085
75%,-0.246297,-0.085351,1.015999,-0.272599,0.434551,0.284384,0.889018,0.616545,-0.408041,0.004531,0.806576,0.441052,0.352809
max,3.966816,3.589637,2.117615,3.668398,2.732346,3.476688,1.117494,3.287300,1.661245,1.530926,1.268938,0.441052,3.548771

In [9]:
df[df.columns[0]]=(df[df.columns[0]]-df[df.columns[0]].mean())/(df[df.columns[0]].max()-df[df.columns[0]].min())
df[df.columns[1]]=(df[df.columns[1]]-df[df.columns[1]].mean())/(df[df.columns[1]].max()-df[df.columns[1]].min())
df[df.columns[2]]=(df[df.columns[2]]-df[df.columns[2]].mean())/(df[df.columns[2]].max()-df[df.columns[2]].min())
df[df.columns[3]]=(df[df.columns[3]]-df[df.columns[3]].mean())/(df[df.columns[3]].max()-df[df.columns[3]].min())
df[df.columns[4]]=(df[df.columns[4]]-df[df.columns[4]].mean())/(df[df.columns[4]].max()-df[df.columns[4]].min())
df[df.columns[5]]=(df[df.columns[5]]-df[df.columns[5]].mean())/(df[df.columns[5]].max()-df[df.columns[5]].min())
df[df.columns[6]]=(df[df.columns[6]]-df[df.columns[6]].mean())/(df[df.columns[6]].max()-df[df.columns[6]].min())
df[df.columns[7]]=(df[df.columns[7]]-df[df.columns[7]].mean())/(df[df.columns[7]].max()-df[df.columns[7]].min())
df[df.columns[8]]=(df[df.columns[8]]-df[df.columns[8]].mean())/(df[df.columns[8]].max()-df[df.columns[8]].min())
df[df.columns[9]]=(df[df.columns[9]]-df[df.columns[9]].mean())/(df[df.columns[9]].max()-df[df.columns[9]].min())
df[df.columns[10]]=(df[df.columns[10]]-df[df.columns[10]].mean())/(df[df.columns[10]].max()-df[df.columns[10]].min())
df[df.columns[11]]=(df[df.columns[11]]-df[df.columns[11]].mean())/(df[df.columns[11]].max()-df[df.columns[11]].min())
df[df.columns[12]]=(df[df.columns[12]]-df[df.columns[12]].mean())/(df[df.columns[12]].max()-df[df.columns[12]].min())
df.to_csv('boston_test_modify.csv',index=False)

In [10]:
df.describe()

,2.91816626,-0.48772236,1.01599907,-0.27259857,0.36544404,-1.60934343,1.11749449,-1.04849446,1.66124525,1.53092646,0.80657583,-1.59755122,1.04106182
count,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02,1.260000e+02
mean,1.514441e-18,-2.202823e-18,4.846212e-18,1.552991e-17,6.167906e-18,-6.608470e-19,5.286776e-18,3.083953e-18,9.692423e-18,1.101412e-19,-4.405647e-19,-3.524518e-18,9.912706e-19
std,1.654239e-01,2.473505e-01,2.568573e-01,2.138090e-01,2.418995e-01,1.519418e-01,3.112906e-01,2.019399e-01,3.540431e-01,3.260009e-01,2.529598e-01,2.185254e-01,1.897656e-01
min,-7.640829e-02,-1.187552e-01,-3.920553e-01,-4.761905e-02,-3.222815e-01,-4.551147e-01,-6.284870e-01,-2.803318e-01,-3.174603e-01,-4.100750e-01,-6.647287e-01,-9.124028e-01,-2.839369e-01
25%,-7.497201e-02,-1.187552e-01,-2.126190e-01,-4.761905e-02,-2.060989e-01,-7.376523e-02,-3.364657e-01,-1.689177e-01,-1.870255e-01,-2.259746e-01,-1.763566e-01,4.667857e-02,-1.222253e-01
50%,-7.224505e-02,-1.187552e-01,-7.883577e-02,-4.761905e-02,-5.049727e-02,-5.910424e-03,5.927896e-02,-4.437864e-02,-1.435473e-01,-1.611211e-01,4.457364e-02,7.725878e-02,-4.428699e-02
75%,-3.743092e-02,-2.007101e-02,3.082226e-01,-4.761905e-02,1.258513e-01,5.638519e-02,3.031619e-01,1.327990e-01,-1.000690e-01,5.226805e-02,2.189922e-01,8.759717e-02,8.255380e-02
max,9.235917e-01,8.812448e-01,6.079447e-01,9.523810e-01,6.777185e-01,5.448853e-01,3.715130e-01,7.196682e-01,6.825397e-01,5.899250e-01,3.352713e-01,8.759717e-02,7.160631e-01